@Base_url=http://localhost:3001/api 

###  @name login
POST {{Base_url}}/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "asdasd"
}


### @name register
POST {{Base_url}}/auth/register
Content-Type: application/json

{
    "name": "Son Nguyen",
    "email": "admin@gmail.com",
    "password": "asdasd",
    "confirm_password": "asdasd"
}

###
GET {{Base_url}}/auth/posts?display=public  
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiIwNWQ5NTBlNy1hZjMxLTQzMDQtOTY2YS1lY2JjNGJmOWZiZDQiLCJyb2xlIjowLCJpYXQiOjE2OTUxNzE5NTMsImV4cCI6MTY5NTE3OTE1M30.GQEtV1QX3DJ5aCInP65Ky9CLeVnH-TSy4RdkcHvHYS0


###############################
#                             #
#          images             #
#                             #
###############################

GET {{Base_url}}/auth/gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiI5OGMyYTE1Mi0xMTBiLTRiYmUtOGM0ZS1kYmUwNmQ4Y2E1Y2MiLCJyb2xlIjowLCJpYXQiOjE2OTUwNDIzNTIsImV4cCI6MTY5NTA0OTU1Mn0.JgcvpZR17NVYDx-1zGLSMLXmUbw_39CXuEr_VuFw5DI


### @name authGetPostById
GET {{Base_url}}/auth/posts/6501a844ec9b92f4d2bcf88c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiI2YWQzYjk4OS1lNWVmLTQzYWItYjAwNi1kYzkzMDQ1MTU2YWQiLCJyb2xlIjowLCJpYXQiOjE2OTQ2NjQ1NzQsImV4cCI6MTY5NDY3MTc3NH0.n14NxTMTLiEdabhOai7wJOtexDF7yMtRQiAA_QNt5x4


###############################
#                             #
#          post               #
#                             #
###############################

### @name CreatePost
Post {{Base_url}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiI2YWQzYjk4OS1lNWVmLTQzYWItYjAwNi1kYzkzMDQ1MTU2YWQiLCJyb2xlIjowLCJpYXQiOjE2OTQ2NjQ1NzQsImV4cCI6MTY5NDY3MTc3NH0.n14NxTMTLiEdabhOai7wJOtexDF7yMtRQiAA_QNt5x4

{
    "title": "Hello world",
    "content": "Hello, i'm Son Nguyen. Welcome to my blog.",
    "description": "Hello, i'm Son Nguyen. Welcome to my blog.",
    "display": "public",
    "hashtags": ["asp.net", "TypeScript", "Wordpress", "Windows", "PostgreSQL"]
}


### @name GetPosts
GET {{Base_url}}/posts?page=1&limit=10
Content-Type: application/json

### @name getPostById
GET {{Base_url}}/posts/6501a844ec9b92f4d2bcf88c
Content-Type: application/json


### @name DeletePost
DELETE  {{Base_url}}/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiIxMjJiNjAzYi01NmVkLTQ0ZTItODVmYy0zY2YxM2RkMGM1MTMiLCJyb2xlIjowLCJpYXQiOjE2OTQxNzQ0MjUsImV4cCI6MTY5NDM0NzIyNX0.6PH_oKCRln_bvWU03gozamu-UBOgU3CemKys8Qf0HfY

### @name updatePost
PATCH   {{Base_url}}/posts/6501a844ec9b92f4d2bcf88c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiJkMjc2OGE2MC02NWM3LTRhNGItOWQyNi05YzY2YmQxOWFlNTAiLCJyb2xlIjowLCJpYXQiOjE2OTQ2MDc0MDMsImV4cCI6MTY5NDYxNDYwM30.RkzqbFUIHKGib4Dnn6E2b7Anali7XZu6pIhJqyRwvaw

{
    "content" : "hello world"
}


### @name searchPosts
GET {{Base_url}}/posts/search?q=te
Content-Type: application/json



###############################
#                             #
#          Comments           #
#                             #
###############################


### @name getComments
GET     {{Base_url}}/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiIwZjcyYjAzNC0zMjdmLTRkMjktYjBkNy03MTBlMGIwNDUyNjciLCJpYXQiOjE2OTQwMDU1NjUsImV4cCI6MTY5NDE3ODM2NX0._QN9aRieLTUHVlrXM7otkRszcb2rcLmfprqkTWsxRH4


### @name createComment
POST    {{Base_url}}/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsIl9pZCI6IjY0ZjcwOWYyNTdiZTA5N2ZkZmY1ZGYwOSIsInRva2VuSWQiOiIwZjcyYjAzNC0zMjdmLTRkMjktYjBkNy03MTBlMGIwNDUyNjciLCJpYXQiOjE2OTQwMDU1NjUsImV4cCI6MTY5NDE3ODM2NX0._QN9aRieLTUHVlrXM7otkRszcb2rcLmfprqkTWsxRH4

{
    "content": "hello 2",
    "post": "64f87d83375209a8f99b729b",
    "parent": "64f94a7c94ab7196afa9e65b",
    "rootId": "64f94a7c94ab7196afa9e65b"
}

###############################
#                             #
#          Hashtags           #
#                             #
###############################

### @name GetHashtags
GET {{Base_url}}/tags?page=2&limit=10
Content-Type: application/json

### @name GetPostByTagSlug
GET {{Base_url}}/tags/postgresql/posts
Content-Type: application/json


### @name GetTagByTagSlug
GET {{Base_url}}/tags/postgresql
Content-Type: application/json